### ISSUE TITLE
Configurable latency per rule

### ISSUE THREAD

**Issue by ahmetkakici** [asalih/http-auto-responder#2]
As you may know Fiddler's AutoResponder allows us to configure latency per-rule.
That's a great feature while using AutoResponder to mimic real-world requests/responses.
I hope you can have some free time to add this feature.

**Comment by asalih** [comment]
Yes, I always have time to help out a friend :) Btw you can specify the latency while creating a Rule.
![image](https://user-images.githubusercontent.com/4123460/86823705-d8e88a80-c095-11ea-8298-a73753384d2d.png)
