### ISSUE TITLE
Video demo, tutorrial

### ISSUE THREAD

**Issue by xuan2261** [asalih/http-auto-responder#3]
Can you make an introductory video? I don't know how to configure and use it.
Thank you very much.

**Comment by asalih** [comment]
Hello, unfortunately no time to make a video, sorry.
1. Download and extract the release https://github.com/asalih/http-auto-responder/releases/tag/v1.0.0
2. Edit config file which you can find the explanation in readme.
3. Execute it, then navigate the /http-auto-responder
4. The rest is about defining the rules.
